export const TITLE = "Psico Tools";
export const LOGOUT = "Deslogearse";
export const CLOSE = "Cerrar";
export const WELCOME = "Bienvenido";
export const NEW_RECOMMENDATION = "Agregar Recomendacion"
export const RATING = "Puntaje General"
export const RATING_DETAILS = "Selecciona tu puntaje del 1 al 5"
export const RATING_DETAILS_INPUT = "Danos mas detalles acerca de tu experiencia con la materia"
export const SEND = "Enviar"
export const PERIOD = "Cuatrimestre"
export const FIRST_PERIOD = "Primer Custrimestre"
export const SECOND_PERIOD = "Segundo Cuatrimestre"
export const SUMMER = "Verano"
export const WINTER = "Invierno"
export const PERIOD_DETAILS="Seleccione el cuatrimestre en el que hizo la materia"
